[api]
port = 8080
host = "127.0.0.1"
secure = false

[jmap]
enabled = true
basePath = "/jmap"
wellKnown = true

[log]
level = "silly"

[dbs]
# mongodb connection string for the main database
mongo = "mongodb://127.0.0.1:27017/wildduck-test"

# redis connection string
redis = "redis://127.0.0.1:6379/13"

dbname = "wildduck-test"

[imap]
port = 9993
host = "127.0.0.1"

[lmtp]
enabled = true
port = 2424

# enable pwned checks for tests
[pwned]
enabled = true
type = "softfail"
